---
name: Feature
about: Impliment new feature.
title: ''
labels: ''
assignees: ''

---

## Task
Short discription of tasks.

## Goals
- [ ] Goal 1
- [ ] Goal 2

## Additional
(Optional: Zusätzliche Anmerkungen oder Links)

---
**Component:** z.B. Gamefield, Logic, View
